layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Ethical hacking
    web_url: https://tryhackme.com/p/Akzharkyn
    image_url: https://www.mobileworldlive.com/wp-content/uploads/2018/05/shutterstock_527048005-security-lock-privacy-650.jpg

  - name: Nordic nature
    web_url: https://pinterest.se/succulentsfloweringlass
    image_url: https://www.nordicspirits.com/sites/default/files/styles/image_w_600_h_450_scale_crop/public/2018-10/38315528666_f5374fe0c7_o.jpg?itok=K-4uZ3z8

  - name: Terrariums
    web_url: https://patreon.com/terrariums_stockholm
    image_url: https://payload.cargocollective.com/1/2/66785/9297755/Terrariums_800.jpg

#skills:
#  - name: Research
#  - name: Security
#  - name: Test automation
#  - name: Distributed Systems
#  - name: Linux

social_media:
  facebook: akzharkyn.maratovna
  quora: Akzharkyn-Duisembiyeva
  instagram: terrariums.stockholm
  linkedin: akzharkyn-duisembiyeva
  pinterest: succulentsfloweringlass
  patreon: terrariums_stockholm
  stackoverflow: 10411618
  goodreads: akzharkyndm
  hackerrank: akzharkyn
  twitter: c0mm0n3
  tryhackme: Akzharkyn
  ctftime: 77312
  hackthebox: 456817
  medium: aduisembiyeva
