layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Security
    web_url: https://github.com/topics/security
    image_url: https://www.mobileworldlive.com/wp-content/uploads/2018/05/shutterstock_527048005-security-lock-privacy-650.jpg

  - name: Game development
    web_url: https://github.com/topics/test-automation
    image_url: https://executeautomationtest.files.wordpress.com/2017/11/automation-testing.png?w=620

  - name: Edge computing
    web_url: https://github.com/topics/edge-computing
    image_url: https://macchina.io/images/EdgeFog.001.png

skills:
  - name: Research
  - name: Security
  - name: Test automation
  - name: Distributed Systems
  - name: Linux

social_media:
  facebook: akzharkyn.maratovna
  quora: Akzharkyn-Duisembiyeva
  instagram: akzharkyndm
  linkedin: akzharkyn-duisembiyeva
  pinterest: aduisembiyeva
  stackoverflow: 10411618
