layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Ethical hacking
    web_url: https://instagram.com/terrariums.stockholm
    image_url: https://www.mobileworldlive.com/wp-content/uploads/2018/05/shutterstock_527048005-security-lock-privacy-650.jpg

  - name: Nordic nature
    web_url: https://pinterest.se/succulentsfloweringlass
    image_url: https://executeautomationtest.files.wordpress.com/2017/11/automation-testing.png?w=620

  - name: Terrariums
    web_url: https://patreon.com/terrariums_stockholm
    image_url: https://en.wikipedia.org/wiki/Terrarium#/media/File:Ward'scher_Kasten.jpg

#skills:
#  - name: Research
#  - name: Security
#  - name: Test automation
#  - name: Distributed Systems
#  - name: Linux

social_media:
  facebook: akzharkyn.maratovna
  quora: Akzharkyn-Duisembiyeva
  instagram: akzharkyndm
  instagram: terrariums.stockholm
  linkedin: akzharkyn-duisembiyeva
  pinterest: aduisembiyeva
  pinterest: succulentsfloweringlass
  patreon: terrariums_stockholm
  stackoverflow: 10411618
  goodreads: akzharkyndm
  hackerrank: akzharkyn
